# Copyright (C) 2013 Alexandre Rames <alexandre@coreperf.com>

# rejit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
from os.path import join, dirname

Import('env librejit')


basic = env.Program('basic', 'basic.cc', LIBS=[librejit])
env.Alias('basic', basic)
regexdna = env.Program('regexdna', 'regexdna.cc', LIBS=[librejit])
env.Alias('regexdna', regexdna)
regexdna_multithread = env.Program('regexdna-multithread', 'regexdna-multithread.cc', LIBS=[librejit, 'pthread'])
env.Alias('regexdna-multithread', regexdna_multithread)

jrep_libs = [librejit]
if ('sample/jrep' in COMMAND_LINE_TARGETS or 'jrep' in COMMAND_LINE_TARGETS) and 'os' in env and env['os'] == 'macos':
  conf = Configure(env)
  if not conf.CheckLib('argp'):
    print 'help argp'
    Exit(1)
  env = conf.Finish()
  jrep_libs += ['argp']
jrep_CXXFLAGS = list(env['CXXFLAGS'])
jrep_LINKFLAGS = list(env['LINKFLAGS'])
if env['os'] == 'linux':
  jrep_CXXFLAGS += ['-D_GLIBCXX_GTHREAD_USE_WEAK=0']
  jrep_LINKFLAGS += ['-pthread']
jrep = env.Program('jrep', 'jrep.cc', LIBS=jrep_libs, CXXFLAGS=jrep_CXXFLAGS, LINKFLAGS=jrep_LINKFLAGS)
env.Alias('jrep', jrep)
